import { StyleSheet } from "react-native";
import Colors from "@/constants/Colors";

export const styles = StyleSheet.create({
    formContainer: {
        width: "100%",
        gap: 20,
        backgroundColor: Colors.background,
        borderRadius: 20,
        elevation: 4,
        // Sombra para iOS
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
    },
    title: {
        fontSize: 24,
        fontFamily: "Montserrat-Bold",
        color: Colors.primaryText,
        marginTop: 16,
        textAlign: "center",
        letterSpacing: 1,
    },
    category: {
        fontSize: 18,
        fontFamily: "Montserrat-SemiBold",
        color: Colors.primaryText,
        marginBottom: 8,
        letterSpacing: 0.5,
    },
    input: {
        fontSize: 18,
        fontFamily: "Montserrat-Regular",
        paddingHorizontal: 16,
        height: 48,
        backgroundColor: Colors.inputBackground,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: Colors.inputBorder,
        color: Colors.primaryText,
    },
    picker: {
        height: 48,
        width: "100%",
        backgroundColor: Colors.inputBackground,
        color: Colors.primaryText,
        borderRadius: 12,
        borderWidth: 2,
        borderColor: Colors.inputBorder,
        marginBottom: 12,
        fontFamily: "Montserrat-Regular",
    },
    error: {
        color: Colors.error,
        textAlign: "center",
        marginTop: 8,
        fontFamily: "Montserrat-SemiBold",
    },
    selectedParamRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 8,
        gap: 8,
        backgroundColor: Colors.inputBackground,
        borderRadius: 10,
        paddingVertical: 6,
        paddingHorizontal: 8,
        borderWidth: 1,
        borderColor: Colors.inputBorder,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.05,
        shadowRadius: 2,
        elevation: 1,
    },
    removeButton: {
        marginLeft: 8,
        paddingHorizontal: 12,
        paddingVertical: 6,
        backgroundColor: Colors.error,
        borderRadius: 20,
        alignItems: "center",
        justifyContent: "center",
        minWidth: 32,
    },
    removeButtonText: {
        color: "#fff",
        fontFamily: "Montserrat-SemiBold",
        fontSize: 13,
    },
});